FROM flexberry/alt.p8-postgresql

COPY SQL/PostgreSql.create.sql /

RUN	cd / ; \
	/docker-cmd.sh& \
	echo "CREATE DATABASE flexberry;" > create.sql ; \
	echo "CREATE USER flexberryuser WITH password 'jhv';" >> create.sql ; \
	echo "GRANT ALL privileges ON DATABASE flexberry TO flexberryuser;" >> create.sql ; \
	until psql -U postgres <create.sql; do echo "Wait...";sleep 2; done ; \
	until psql -U flexberryuser -d flexberry < PostgreSql.create.sql; do echo "Wait...";sleep 5; done ; \
	/etc/init.d/postgresql stop;  while su -c psql postgres </dev/null >/dev/null 2>&1; do sleep 1; done;  \
	echo "postgresql stopped"
