FROM flexberry/alt.p8-postgresql

COPY SQL/PostgreSql.create.sql /

RUN	cd / ; \
	/docker-cmd.sh& \
	echo "CREATE DATABASE flexberry;" > create.sql ; \
	echo "CREATE USER flexberryuser WITH password 'jhv';" >> create.sql ; \
	echo "GRANT ALL privileges ON DATABASE flexberry TO flexberryuser;" >> create.sql ; \
	until psql -U postgres <create.sql; do echo "Wait...";sleep 2; done ; \
	until psql -U flexberryuser -d flexberry < PostgreSql.create.sql; do echo "Wait...";sleep 5; done ; \
	/etc/init.d/postgresql stop; \
  sleep 5; \
  while [ -f /var/lib/pgsql/data/postmaster.pid ]; do sleep 5; done; \
  killall postgres; \
  while [ -f /tmp/.s.PGSQL.5432.lock ]; do sleep 5; done; \
	echo "postgresql stopped"
